src/NetSendGridEmailClient.Web/Controllers/EmailController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using NetSendGridEmailClient.Interface;

namespace NetSendGridEmailClient.Web.Controllers;

[GoogleScopedAuthorize]
[Authorize(Policy = "Admin")]
public class EmailController : Controller
{
    private readonly ILogger<EmailController> _logger;

    private readonly SendGridSettings _sendGridSettings;

    private readonly EmailPayloadValidator _emailPayloadValidator;

    private readonly IEmailPayloadFactory _emailPayloadFactory;

    private readonly IEmailService _emailService;

    private readonly IMarkdownService _markdownService;

    public EmailController(
        ILogger<EmailController> logger,
        SendGridSettings sendGridSettings,
        EmailPayloadValidator emailPayloadValidator,
        IEmailPayloadFactory emailPayloadFactory,
        IEmailService emailService,
        IMarkdownService markdownService
        )
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _sendGridSettings = sendGridSettings ?? throw new ArgumentNullException(nameof(sendGridSettings));
        _emailPayloadValidator = emailPayloadValidator ?? throw new ArgumentNullException(nameof(emailPayloadValidator));
        _emailPayloadFactory = emailPayloadFactory ?? throw new ArgumentNullException(nameof(emailPayloadFactory));
        _emailService = emailService ?? throw new ArgumentNullException(nameof(emailService));
        _markdownService = markdownService ?? throw new ArgumentNullException(nameof(markdownService));
    }

    protected IActionResult SendToEditor(EmailPayload model)
    {
        ViewBag.FromDomain = new SelectList(
            _sendGridSettings
            .Domains
            .Select(x => x.Domain)
        );
        return View("Index", model);
    }

    public IActionResult Index() =>
        SendToEditor(_emailPayloadFactory.New<EmailPayload>());

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Compose(EmailPayload model) =>
        SendToEditor(model);

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Confirm(EmailPayload model)
    {
        _emailPayloadValidator
            .Validate(model)
            .AddToModelState(ModelState);

        model.HtmlBody = _markdownService.RenderHtml(model.Body);

        if (!ModelState.IsValid)
            return SendToEditor(model);

        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Send(EmailPayload model)
    {
        _emailPayloadValidator
            .Validate(model)
            .AddToModelState(ModelState);

        if (!ModelState.IsValid)
            return SendToEditor(model);

        var result = await _emailService.SendAsync(model);

        if(result.IsFaulted)
        {
            ModelState.AddModelError("SendGrid", result.Exception.Message.ToString());
            return SendToEditor(model);
        }

        return View("Sent");
    }
}

src/NetSendGridEmailClient.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NET SendGrid Email Client</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/css/bootstrap.min.css" integrity="sha512-XWTTruHZEYJsxV3W/lSXG1n3Q39YIWOstqvmFsdNEEQfHoZ6vm6E9GK2OrF6DSJSpIbRbi+Nn0WDPID9O7xB2Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/js/bootstrap.min.js" integrity="sha512-8Y8eGK92dzouwpROIppwr+0kPauu0qqtnzZZNEF8Pat5tuRNJxJXCkbQfJ0HlUG3y1HB3z18CSKmUo7i2zcPpg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NET SendGrid Email Client</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsLoggedIn())
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Email" asp-action="">Compose Email</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogOut">Sign Out</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; @DateTime.Now.Year • NET SendGrid Email Client •
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> •
            <a asp-area="" asp-controller="Home" asp-action="TermsOfService">Terms of Service</a>
        </div>
    </footer>

</body>
</html>